{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.4.11"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.11.jar",
          "url": "spring-boot-starter-test-3.4.11.jar",
          "size": 4792,
          "sha512": "e91afc9db24041f56e0dd43eb510a7f314db32197a9f2c635d2a4d96cc2fbf68849d30d22b52fab82c7ca311233870733f15489e264216ea2241762c5ef0fdb9",
          "sha256": "e905c9ddd6b406afa71b62de31a30d0f0ed4bb2fe86e6c29df4ff26bf6f14093",
          "sha1": "1cedb3eb215c714a6fd3205615d6ed771be35e5f",
          "md5": "759ae4351e290aa027d8f8f351cdd340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.4.11"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.11.jar",
          "url": "spring-boot-starter-test-3.4.11.jar",
          "size": 4792,
          "sha512": "e91afc9db24041f56e0dd43eb510a7f314db32197a9f2c635d2a4d96cc2fbf68849d30d22b52fab82c7ca311233870733f15489e264216ea2241762c5ef0fdb9",
          "sha256": "e905c9ddd6b406afa71b62de31a30d0f0ed4bb2fe86e6c29df4ff26bf6f14093",
          "sha1": "1cedb3eb215c714a6fd3205615d6ed771be35e5f",
          "md5": "759ae4351e290aa027d8f8f351cdd340"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.11-javadoc.jar",
          "url": "spring-boot-starter-test-3.4.11-javadoc.jar",
          "size": 4792,
          "sha512": "1bb8acba9547f476000231f6871d80ad7dd8275d3d61a34d6bf0c113f77176c90815792ea92e8b6299472ac7e12fffd7ff4914b7ed27f262bb3f3e5defc6ac2a",
          "sha256": "226070ae1f2235f0898aebd870175407e45c25cf062cf87130b584353a39616c",
          "sha1": "7fba335f3053dbc9f604474e8ff00664affc824b",
          "md5": "04e39dc8b7a665405f6b1c398a56561a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.4.11-sources.jar",
          "url": "spring-boot-starter-test-3.4.11-sources.jar",
          "size": 4792,
          "sha512": "1bb8acba9547f476000231f6871d80ad7dd8275d3d61a34d6bf0c113f77176c90815792ea92e8b6299472ac7e12fffd7ff4914b7ed27f262bb3f3e5defc6ac2a",
          "sha256": "226070ae1f2235f0898aebd870175407e45c25cf062cf87130b584353a39616c",
          "sha1": "7fba335f3053dbc9f604474e8ff00664affc824b",
          "md5": "04e39dc8b7a665405f6b1c398a56561a"
        }
      ]
    }
  ]
}
